# Generated by Django 5.1.3 on 2025-09-09 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID ссылки')),
                ('original_url', models.URLField(help_text='Введите полный URL, который нужно сократить', max_length=255, unique=True, verbose_name='Оригинальная ссылка')),
                ('short_code', models.CharField(help_text='Автоматически генерируемый код длиной 6–10 символов', max_length=10, unique=True, verbose_name='Короткий код')),
                ('clicks', models.IntegerField(default=0, help_text='Сколько раз по этой ссылке переходили', verbose_name='Количество переходов')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если указана, ссылка перестанет работать после этой даты', null=True, verbose_name='Дата истечения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
